"""Publication-level bias ratings — data, normalisation, seeding.

Everything about outlet bias ratings that isn't SQL lives here:

  * ``BiasRatingRecord`` — a plain dataclass for a single external rating.
  * ``RATINGS`` — the current, verifiable rating table for our outlets,
    hand-recorded from external documented sources (never generated by
    an LLM or by any NewsLens component).
  * ``normalize_label(source, label)`` — deterministic mapping from an
    external label to the visualisation buckets ('left'/'center'/'right').
    Returns ``None`` when the label can't be mapped safely; the caller
    treats that as ``unrated`` rather than inventing a category.
  * ``seed_bias_ratings()`` — idempotent upsert of ``RATINGS`` into the
    ``outlet_bias_ratings`` table. Safe to run repeatedly; replaces a
    row in place when the external label changes.

Adding a new rating source
--------------------------
1. Verify the rating on the source's own page (URL captured below).
2. Append an entry to ``RATINGS`` with the exact published label.
3. If the source uses a label ``normalize_label()`` doesn't yet know,
   add the mapping to ``_SOURCE_LABEL_MAP`` — do NOT stretch an existing
   mapping to cover it.
4. Re-run ``python -m src.ingestion.seed_bias_ratings``.
"""

from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import dataclass
from datetime import date, datetime, timezone
from typing import Literal

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

BiasCategory = Literal["left", "center", "right"]


@dataclass(frozen=True)
class BiasRatingRecord:
    """One hand-recorded rating from an external source."""

    outlet_slug: str
    source: str                   # e.g. "MBFC", "AdFontes"
    original_label: str           # verbatim from the source's page
    rating_url: str               # link to the source's page for verification
    rated_at: date | None         # source's "last updated" date, when known


# ---------------------------------------------------------------------------
# Ratings table (v1: MBFC only)
#
# Every row was verified on the source's own page. The `original_label`
# is the exact text the source publishes. NewsLens does NOT generate any
# of these ratings.
#
# Note about NDTV: MBFC currently rates NDTV as "Right-Center", with
# the source page dated 2024-12-30. NewsLens records the published
# rating without independently interpreting the reason for that
# classification.
# ---------------------------------------------------------------------------

RATINGS: tuple[BiasRatingRecord, ...] = (
    # The Hindu — https://mediabiasfactcheck.com/the-hindu/
    BiasRatingRecord(
        outlet_slug="the-hindu",
        source="MBFC",
        original_label="Left-Center",
        rating_url="https://mediabiasfactcheck.com/the-hindu/",
        rated_at=date(2023, 7, 1),
    ),
    # Times of India — https://mediabiasfactcheck.com/times-of-india/
    BiasRatingRecord(
        outlet_slug="times-of-india",
        source="MBFC",
        original_label="Right-Center",
        rating_url="https://mediabiasfactcheck.com/times-of-india/",
        rated_at=date(2024, 12, 13),
    ),
    # Indian Express — https://mediabiasfactcheck.com/the-indian-express/
    BiasRatingRecord(
        outlet_slug="indian-express",
        source="MBFC",
        original_label="Left-Center",
        rating_url="https://mediabiasfactcheck.com/the-indian-express/",
        rated_at=date(2026, 5, 1),
    ),
    # NDTV — https://mediabiasfactcheck.com/ndtv/
    BiasRatingRecord(
        outlet_slug="ndtv",
        source="MBFC",
        original_label="Right-Center",
        rating_url="https://mediabiasfactcheck.com/ndtv/",
        rated_at=date(2024, 12, 30),
    ),
    # Hindustan Times — https://mediabiasfactcheck.com/hindustan-times/
    BiasRatingRecord(
        outlet_slug="hindustan-times",
        source="MBFC",
        original_label="Left-Center",
        rating_url="https://mediabiasfactcheck.com/hindustan-times/",
        rated_at=date(2024, 12, 13),
    ),
)


# ---------------------------------------------------------------------------
# Source priority — which source's rating "wins" per outlet
#
# The bar's distribution uses one primary rating per outlet. When several
# sources rate the same outlet, the first entry here that has a rating
# for that outlet is chosen. Documented so the choice is auditable, not
# opaque.
# ---------------------------------------------------------------------------

SOURCE_PRIORITY: tuple[str, ...] = (
    "MBFC",
    # Add "AdFontes" here (or ahead of MBFC) once its ratings are recorded.
)


# ---------------------------------------------------------------------------
# Normalisation
# ---------------------------------------------------------------------------

# Per-source label → category map. Keyed by (source, lowered-stripped label).
# The comments spell out why each label maps where it does — the mapping
# is deterministic and small on purpose.
_SOURCE_LABEL_MAP: dict[str, dict[str, BiasCategory]] = {
    "MBFC": {
        # https://mediabiasfactcheck.com/about/ describes the labels MBFC
        # uses. We map the four that appear on the outlets we track.
        "left": "left",
        "left-center": "left",       # aka Lean Left
        "least biased": "center",    # MBFC's centre category
        "center": "center",
        "right-center": "right",     # aka Lean Right
        "right": "right",
    },
    # Ad Fontes: recorded on the same axis (Left / Skews Left / Middle /
    # Skews Right / Right). Filled in when we add Ad Fontes rows.
    "AdFontes": {
        "left": "left",
        "skews left": "left",
        "middle": "center",
        "skews right": "right",
        "right": "right",
    },
}


def normalize_label(source: str, label: str) -> BiasCategory | None:
    """Map an external rating label to a visualisation bucket.

    Returns one of ``'left'`` / ``'center'`` / ``'right'`` when the
    label is a known category for the given source, or ``None`` when
    the label can't be mapped safely (e.g. an unfamiliar variant, or a
    source we haven't seen before). ``None`` means "treat this outlet
    as unrated for the bar" — never invent a category.
    """
    source_key = source.strip()
    label_key = (label or "").strip().lower()
    if not label_key:
        return None
    src_map = _SOURCE_LABEL_MAP.get(source_key)
    if src_map is None:
        return None
    return src_map.get(label_key)


# ---------------------------------------------------------------------------
# Seeding
# ---------------------------------------------------------------------------

def seed_bias_ratings(records: tuple[BiasRatingRecord, ...] = RATINGS) -> dict[str, int]:
    """Idempotent upsert of every record in ``records``.

    Skips outlets that don't exist in the database (with a warning). If
    an existing row's ``original_label`` has changed at the source, the
    row is replaced in place; otherwise it's left alone.

    Returns a summary dict: ``{'inserted': int, 'updated': int,
    'unchanged': int, 'skipped_no_outlet': int, 'skipped_unmappable': int}``.
    """
    # Deferred imports so this module can be imported by pure-Python
    # code (normalize_label, SOURCE_PRIORITY, the dataclass) without
    # pulling in SQLAlchemy / the DB models / pydantic-settings.
    from sqlalchemy import create_engine, select
    from sqlalchemy.dialects.postgresql import insert as pg_insert

    from src.config import get_settings
    from src.db.models import Outlet, OutletBiasRating

    engine = create_engine(get_settings().sync_database_url, pool_pre_ping=True)
    summary = {
        "inserted": 0,
        "updated": 0,
        "unchanged": 0,
        "skipped_no_outlet": 0,
        "skipped_unmappable": 0,
    }

    with engine.begin() as conn:
        # Build a slug → id map once so we can attach each rating.
        slug_to_id = {
            row.slug: row.id
            for row in conn.execute(select(Outlet.id, Outlet.slug)).all()
        }

        for rec in records:
            outlet_id = slug_to_id.get(rec.outlet_slug)
            if outlet_id is None:
                log.warning(
                    "outlet not present, skipping rating source=%s slug=%s",
                    rec.source, rec.outlet_slug,
                )
                summary["skipped_no_outlet"] += 1
                continue

            normalized = normalize_label(rec.source, rec.original_label)
            if normalized is None:
                log.warning(
                    "unmappable label, skipping rating source=%s slug=%s label=%r",
                    rec.source, rec.outlet_slug, rec.original_label,
                )
                summary["skipped_unmappable"] += 1
                continue

            rated_at_ts = (
                datetime.combine(rec.rated_at, datetime.min.time(), tzinfo=timezone.utc)
                if rec.rated_at is not None else None
            )

            # Look up any existing row for this (outlet, source).
            existing = conn.execute(
                select(
                    OutletBiasRating.id,
                    OutletBiasRating.original_label,
                    OutletBiasRating.normalized_category,
                    OutletBiasRating.rating_url,
                    OutletBiasRating.rated_at,
                ).where(
                    OutletBiasRating.outlet_id == outlet_id,
                    OutletBiasRating.source == rec.source,
                )
            ).first()

            if existing is None:
                stmt = pg_insert(OutletBiasRating).values(
                    outlet_id=outlet_id,
                    source=rec.source,
                    original_label=rec.original_label,
                    normalized_category=normalized,
                    rating_url=rec.rating_url,
                    rated_at=rated_at_ts,
                )
                conn.execute(stmt)
                summary["inserted"] += 1
                log.info(
                    "inserted bias rating source=%s slug=%s label=%r → %s",
                    rec.source, rec.outlet_slug, rec.original_label, normalized,
                )
                continue

            # Compare and decide whether an update is warranted. We
            # replace when ANY field would change (label, mapping, URL,
            # rated_at) so a re-verified rating date propagates too.
            existing_rated_at = existing.rated_at
            needs_update = (
                existing.original_label != rec.original_label
                or existing.normalized_category != normalized
                or existing.rating_url != rec.rating_url
                or existing_rated_at != rated_at_ts
            )
            if needs_update:
                conn.execute(
                    OutletBiasRating.__table__.update()
                    .where(OutletBiasRating.id == existing.id)
                    .values(
                        original_label=rec.original_label,
                        normalized_category=normalized,
                        rating_url=rec.rating_url,
                        rated_at=rated_at_ts,
                    )
                )
                summary["updated"] += 1
                log.info(
                    "updated bias rating source=%s slug=%s",
                    rec.source, rec.outlet_slug,
                )
            else:
                summary["unchanged"] += 1

    engine.dispose()
    return summary


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Seed publication-level bias ratings from external sources.",
    )
    ap.parse_args()

    from src.ingestion.log import setup_logging  # deferred; see seed_bias_ratings
    setup_logging()
    summary = seed_bias_ratings()
    log.info(
        "seed_bias_ratings complete: inserted=%d updated=%d unchanged=%d "
        "skipped_no_outlet=%d skipped_unmappable=%d",
        summary["inserted"],
        summary["updated"],
        summary["unchanged"],
        summary["skipped_no_outlet"],
        summary["skipped_unmappable"],
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
