import { useMemo } from "react";

import type {
  ArticleInStory,
  StoryComparisonPayload,
} from "@/api/types";

import { coverageGapsFromMatrix } from "./helpers";
import { StorySection } from "./primitives";

/**
 * FEATURE 7 — Coverage Gaps
 *
 * Renders ``story_comparisons.not_present_here``. The critical
 * responsibility here is language: NewsLens never claims an outlet
 * "ignored", "omitted" or "withheld" anything. The wording is
 * strictly observational:
 *
 *   - Section title: "Not observed in some outlets"
 *   - Per-outlet heading: "Not observed in <Outlet>"
 *   - Item lede: "Observed in other analyzed coverage but not here."
 *
 * The reader can draw their own conclusions; NewsLens only reports
 * what was and was not observed in the analyzed articles for this
 * story.
 *
 * NOTE on the LLM output: the ``not_present_here`` payload is
 * generated by the compare prompt. If that prompt happens to produce
 * strings that themselves use accusatory language ("ignored X"), we
 * cannot rewrite them here — the frontend surrounds the items with
 * observational framing but the item strings are preserved verbatim.
 */
export function CoverageGaps({
  comparison,
  articles,
}: {
  comparison: StoryComparisonPayload | null;
  articles: ArticleInStory[];
}) {
  const rows = useMemo(
    () =>
      coverageGapsFromMatrix(comparison?.not_present_here ?? null, articles),
    [comparison?.not_present_here, articles],
  );

  const hasAny = rows.some((r) => r.items.length > 0);
  if (!hasAny) return null;

  return (
    <StorySection
      eyebrow="Coverage gaps"
      title="What each outlet did not cover"
      lede="Points observed in other analyzed coverage of this story but not observed in the outlet named. NewsLens reports observations only — it does not imply intent."
    >
      <div className="grid grid-cols-1 gap-x-10 gap-y-8 md:grid-cols-2">
        {rows.map((row) => (
          <article key={row.slug} className="border-t border-ink-primary/15 pt-5">
            <header className="mb-3">
              <div className="text-[10.5px] font-semibold uppercase tracking-[0.14em] text-ink-muted">
                Not observed in
              </div>
              <div className="mt-0.5 font-display text-[19px] leading-tight text-ink-primary">
                {row.name}
              </div>
            </header>
            {row.items.length === 0 ? (
              <p className="text-[12.5px] text-ink-muted">
                No coverage gaps observed relative to other outlets.
              </p>
            ) : (
              <ul className="space-y-3 text-[14px] leading-[1.6] text-ink-secondary">
                {row.items.map((item, i) => (
                  <li key={i} className="flex gap-3">
                    <span
                      aria-hidden
                      className="mt-[9px] inline-block h-[3px] w-[3px] shrink-0 rounded-full bg-accent"
                    />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            )}
          </article>
        ))}
      </div>
      <p className="mt-8 max-w-3xl text-[11.5px] leading-relaxed text-ink-muted">
        These are observations from the article-level analysis available at
        the time of comparison. Absence from analyzed coverage is not evidence
        of an outlet's editorial choice — the story may have been covered
        elsewhere, later, or in a format not yet analyzed.
      </p>
    </StorySection>
  );
}
